In [1]:
import psycopg2

In [2]:
import pandas as pd
import numpy as np

In [22]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\lenovo\anaconda3\lib\site-packages (2.9.10)
Note: you may need to restart the kernel to use updated packages.

In [24]:
# csv to dataframe
df_buses_1=pd.read_csv("Kerala Bus details.csv")
df_buses_2=pd.read_csv("Andhra Bus details.csv")
df_buses_3=pd.read_csv("Telangana Bus details.csv")
df_buses_4=pd.read_csv("Rajasthan Bus details.csv")
df_buses_5=pd.read_csv("Bihar Bus details.csv")
df_buses_6=pd.read_csv("South Bengal Bus details.csv")
df_buses_7=pd.read_csv("Himachal_pradesh Bus details.csv")
df_buses_8=pd.read_csv("Chandigarh Bus details.csv")
df_buses_9=pd.read_csv("Uttar pradesh Bus details.csv")
df_buses_10=pd.read_csv("Punjab  Bus details.csv")

Final_df=pd.concat([df_buses_1,df_buses_2,df_buses_3,df_buses_4,df_buses_5,df_buses_6,
                    df_buses_7,df_buses_8,df_buses_9,df_buses_10],ignore_index=True)
Final_df

,Unnamed: 0,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name
0,0,KSRTC (Kerala) - 2132,Swift Deluxe Non AC Air Bus (2+2),07:30,15:50,08h 20m,INR 740,15 Seats available,2.8\n9,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
1,1,KSRTC (Kerala) - 580,Super Express Non AC Seater Air Bus (2+2),08:05,16:45,08h 40m,INR 606,7 Seats available,3.1\n41,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
2,2,KSRTC (Kerala) - 53,SWIFT-GARUDA A/C SEATER BUS,08:30,17:05,08h 35m,INR 945,22 Seats available,4.0\n85,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
3,3,KSRTC (Kerala) - 579,Super Express Non AC Seater Air Bus (2+2),10:00,18:30,08h 30m,INR 606,3 Seats available,4.1\n43,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
4,4,KSRTC (Kerala) - 55,SWIFT-GARUDA A/C SEATER BUS,12:00,20:20,08h 20m,INR 945,28 Seats available,3.9\n69,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
...,...,...,...,...,...,...,...,...,...,...,...
6723,883,Indo Canadian Transport Company,A/C Sleeper (2+1),08:00,19:00,11h 00m,INR 3850,37 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6724,884,Indo Canadian Transport Company,Mercedes A/C Semi Sleeper (2+2),16:00,03:00,11h 00m,INR 3300,51 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6725,885,Banjara Satguru Travels,A/C Seater / Sleeper (2+1),22:00,06:25,08h 25m,INR 699,38 Seats available,2.6,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6726,886,CALL2TRIP,A/C Seater / Sleeper (2+2),22:25,06:10,07h 45m,INR 799,18 Seats available,2.0\n1,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6727,887,SHREE SATGURU TRAVELS,A/C Seater / Sleeper (2+2),22:07,05:50,07h 43m,INR 599,38 Seats available,1.0\n1,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport

In [25]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6728 entries, 0 to 6727
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       6728 non-null   int64
 1   Bus_name         6728 non-null   object
 2   Bus_type         6728 non-null   object
 3   Start_time       6728 non-null   object
 4   End_time         6728 non-null   object
 5   Total_duration   6728 non-null   object
 6   Price            6728 non-null   object
 7   Seats_Available  6728 non-null   object
 8   Ratings          6728 non-null   object
 9   Route_link       6728 non-null   object
 10  Route_name       6728 non-null   object
dtypes: int64(1), object(10)
memory usage: 578.3+ KB

In [26]:
Final_df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [27]:
Final_df

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name
0,KSRTC (Kerala) - 2132,Swift Deluxe Non AC Air Bus (2+2),07:30,15:50,08h 20m,INR 740,15 Seats available,2.8\n9,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
1,KSRTC (Kerala) - 580,Super Express Non AC Seater Air Bus (2+2),08:05,16:45,08h 40m,INR 606,7 Seats available,3.1\n41,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
2,KSRTC (Kerala) - 53,SWIFT-GARUDA A/C SEATER BUS,08:30,17:05,08h 35m,INR 945,22 Seats available,4.0\n85,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
3,KSRTC (Kerala) - 579,Super Express Non AC Seater Air Bus (2+2),10:00,18:30,08h 30m,INR 606,3 Seats available,4.1\n43,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
4,KSRTC (Kerala) - 55,SWIFT-GARUDA A/C SEATER BUS,12:00,20:20,08h 20m,INR 945,28 Seats available,3.9\n69,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
...,...,...,...,...,...,...,...,...,...,...
6723,Indo Canadian Transport Company,A/C Sleeper (2+1),08:00,19:00,11h 00m,INR 3850,37 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6724,Indo Canadian Transport Company,Mercedes A/C Semi Sleeper (2+2),16:00,03:00,11h 00m,INR 3300,51 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6725,Banjara Satguru Travels,A/C Seater / Sleeper (2+1),22:00,06:25,08h 25m,INR 699,38 Seats available,2.6,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6726,CALL2TRIP,A/C Seater / Sleeper (2+2),22:25,06:10,07h 45m,INR 799,18 Seats available,2.0\n1,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6727,SHREE SATGURU TRAVELS,A/C Seater / Sleeper (2+2),22:07,05:50,07h 43m,INR 599,38 Seats available,1.0\n1,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport

In [28]:
#convert prices to numeric
Final_df["Price"]=Final_df["Price"].str.replace("INR","")
Final_df["Price"]=Final_df["Price"].astype(float)

In [29]:
Final_df["Price"].fillna(0,inplace=True)

In [30]:
Final_df["Price"]

0        740.0
1        606.0
2        945.0
3        606.0
4        945.0
         ...
6723    3850.0
6724    3300.0
6725     699.0
6726     799.0
6727     599.0
Name: Price, Length: 6728, dtype: float64

In [31]:
#convert Ratings to numeric
Final_df["Ratings"]=Final_df["Ratings"].str.replace("New","")
Final_df["Ratings"]=Final_df["Ratings"].str.strip()
Final_df["Ratings"]=Final_df["Ratings"].str.split().str[0]
Final_df["Ratings"] = pd.to_numeric(Final_df["Ratings"], errors='coerce')
Final_df["Ratings"].fillna(0,inplace=True)

In [32]:
Final_df["Ratings"]

0       2.8
1       3.1
2       4.0
3       4.1
4       3.9
       ...
6723    3.5
6724    3.5
6725    2.6
6726    2.0
6727    1.0
Name: Ratings, Length: 6728, dtype: float64

In [33]:
# replacing the nan value
Final_df = Final_df.replace({np.nan: None})

In [34]:
Final_df

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name
0,KSRTC (Kerala) - 2132,Swift Deluxe Non AC Air Bus (2+2),07:30,15:50,08h 20m,740.0,15 Seats available,2.8,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
1,KSRTC (Kerala) - 580,Super Express Non AC Seater Air Bus (2+2),08:05,16:45,08h 40m,606.0,7 Seats available,3.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
2,KSRTC (Kerala) - 53,SWIFT-GARUDA A/C SEATER BUS,08:30,17:05,08h 35m,945.0,22 Seats available,4.0,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
3,KSRTC (Kerala) - 579,Super Express Non AC Seater Air Bus (2+2),10:00,18:30,08h 30m,606.0,3 Seats available,4.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
4,KSRTC (Kerala) - 55,SWIFT-GARUDA A/C SEATER BUS,12:00,20:20,08h 20m,945.0,28 Seats available,3.9,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
...,...,...,...,...,...,...,...,...,...,...
6723,Indo Canadian Transport Company,A/C Sleeper (2+1),08:00,19:00,11h 00m,3850.0,37 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6724,Indo Canadian Transport Company,Mercedes A/C Semi Sleeper (2+2),16:00,03:00,11h 00m,3300.0,51 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6725,Banjara Satguru Travels,A/C Seater / Sleeper (2+1),22:00,06:25,08h 25m,699.0,38 Seats available,2.6,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6726,CALL2TRIP,A/C Seater / Sleeper (2+2),22:25,06:10,07h 45m,799.0,18 Seats available,2.0,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6727,SHREE SATGURU TRAVELS,A/C Seater / Sleeper (2+2),22:07,05:50,07h 43m,599.0,38 Seats available,1.0,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport

In [35]:
df=Final_df.to_csv("Redbus_Final_details.csv")

In [36]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\lenovo\anaconda3\lib\site-packages (2.9.10)
Note: you may need to restart the kernel to use updated packages.

In [37]:
connection = psycopg2.connect(
            user="postgres",  # Replace with your PostgreSQL username
            password="harish26",  # Replace with your PostgreSQL password
            port="5433",  # Replace with your PostgreSQL port
            database="postgres"  # Replace with your PostgreSQL database name
        )
cursor = connection.cursor()

In [38]:
bus_df = pd.DataFrame(Final_df)

In [39]:
Final_df

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name
0,KSRTC (Kerala) - 2132,Swift Deluxe Non AC Air Bus (2+2),07:30,15:50,08h 20m,740.0,15 Seats available,2.8,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
1,KSRTC (Kerala) - 580,Super Express Non AC Seater Air Bus (2+2),08:05,16:45,08h 40m,606.0,7 Seats available,3.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
2,KSRTC (Kerala) - 53,SWIFT-GARUDA A/C SEATER BUS,08:30,17:05,08h 35m,945.0,22 Seats available,4.0,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
3,KSRTC (Kerala) - 579,Super Express Non AC Seater Air Bus (2+2),10:00,18:30,08h 30m,606.0,3 Seats available,4.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
4,KSRTC (Kerala) - 55,SWIFT-GARUDA A/C SEATER BUS,12:00,20:20,08h 20m,945.0,28 Seats available,3.9,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Bangalore
...,...,...,...,...,...,...,...,...,...,...
6723,Indo Canadian Transport Company,A/C Sleeper (2+1),08:00,19:00,11h 00m,3850.0,37 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6724,Indo Canadian Transport Company,Mercedes A/C Semi Sleeper (2+2),16:00,03:00,11h 00m,3300.0,51 Seats available,3.5,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6725,Banjara Satguru Travels,A/C Seater / Sleeper (2+1),22:00,06:25,08h 25m,699.0,38 Seats available,2.6,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6726,CALL2TRIP,A/C Seater / Sleeper (2+2),22:25,06:10,07h 45m,799.0,18 Seats available,2.0,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
6727,SHREE SATGURU TRAVELS,A/C Seater / Sleeper (2+2),22:07,05:50,07h 43m,599.0,38 Seats available,1.0,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport

In [40]:
def insert_data_into_postgresql(data):
    try:
        # Connect to PostgreSQL
        connection = psycopg2.connect(
            user="postgres",  # Replace with your PostgreSQL username
            password="harish26",  # Replace with your PostgreSQL password
            port="5433",  # Replace with your PostgreSQL port
            database="postgres"  # Replace with your PostgreSQL database name
        )
        cursor = connection.cursor()        
        
        # Insert data into PostgreSQL table
        for index, row in data.iterrows():
            insert_query = """
            INSERT INTO bus_details (Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_available,Ratings,Route_links,Route_name)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            record_to_insert = (
                str(row['Bus_name']) if row['Bus_name'] else None,  # Handle None properly
                str(row['Bus_type']) if row['Bus_type'] else None,
                str(row['Start_time']) if row['Start_time'] else None,
                str(row['End_time']) if row['End_time'] else None,
                str(row['Total_duration']) if row['Total_duration'] else None,
                str(row['Price']) if row['Price'] else None,
                str(row['Seats_Available']) if row['Seats_Available'] else None,
                str(row['Ratings']) if row['Ratings'] is not None else None,  # Ensure Ratings is a float
                str(row['Route_link']) if row['Route_link'] else None,
                str(row['Route_name']) if row['Route_name'] else None)
            cursor.execute(insert_query, record_to_insert)
        
        # Commit the transaction
        connection.commit()
        print("Data successfully inserted into PostgreSQL")
    
    except (Exception, psycopg2.Error) as error:
        print(f"Failed to insert data into PostgreSQL: {error}")
    
    finally:
        # Close connection
        if connection:
            cursor.close()
            connection.close()

# Call the function to insert data into PostgreSQL
insert_data_into_postgresql(bus_df)

Data successfully inserted into PostgreSQL